forms:
  bccacontract:
    path: /bcca/contract
    type: issue-credential
    schema_name: contract.bcca
    page_title: Title for contract.bcca
    title: Title for contract.bcca
    template: bcgov.index.html
    description: The contract credential awarded to the General Contractor
    explanation: Use the form below to issue a Credential.
    proof_request:
      id: dflow_registration
      connection_id: bctob
    related_credentials:
      client:
        related_schema: contract_relationship.bcca
        related_schema_version: 1.0.0
        topic: contract_id
        topic_name: contract_name
        related_topic: corp_num
        related_topic_name: legal_name
        effective_date: effective_date
        relationship_type: Client
        relationship_description: Client
        related_relationship_type: Contract
        related_relationship_description: Contract
      consultant:
        related_schema: contract_relationship.bcca
        topic: contract_id
        topic_name: contract_name
        related_topic: consultant_corp_num
        related_topic_name: consultant_legal_name
        effective_date: effective_date
        relationship_type: Consultant
        relationship_description: Project Consultant
        related_relationship_type: Project
        related_relationship_description: Project
      contractor:
        related_schema: contract_relationship.bcca
        topic: contract_id
        topic_name: contract_name
        related_topic: contractor_corp_num
        related_topic_name: contractor_legal_name
        effective_date: effective_date
        relationship_type: Contractor
        relationship_description: General Contractor
        related_relationship_type: Contract
        related_relationship_description: Contract
    fields:
    - name: corp_num
      label: corp_num
      type: text
      required: true
    - name: legal_name
      label: legal_name
      type: text
      required: true
    - name: project_name
      label: project_name
      type: text
      required: true
    - name: project_address
      label: Mailing Address
      type: address
      required: true
    - name: consultant_corp_num
      label: consultant_corp_num
      type: text
      required: true
    - name: consultant_legal_name
      label: consultant_legal_name
      type: text
      required: true
    - name: contractor_corp_num
      label: contractor_corp_num
      type: text
      required: true
    - name: contractor_legal_name
      label: contractor_legal_name
      type: text
      required: true
    - name: contract_name
      label: contract_name
      type: text
      required: true
    - name: contract_start_date
      label: contract_start_date
      type: date
      required: true
    - name: contract_end_date
      label: contract_end_date
      type: date
      required: true
    - name: contract_type
      label: contract_type
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: payment_terms
      label: payment_terms
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: effective_date
      label: effective_date
      type: date
      required: true
    - name: expiry_date
      label: expiry_date
      type: date
      required: false
    mapping:
      attributes:
      - name: contract_id
        from: helper
        source: uuid
  bccasubcontract:
    path: /bcca/subcontract
    type: issue-credential
    schema_name: subcontract.bcca
    page_title: Title for subcontract.bcca
    title: Title for subcontract.bcca
    template: bcgov.index.html
    description: The sub-contract credential awarded to a Trade/Sub
    explanation: Use the form below to issue a Credential.
    proof_request:
      id: bcca_contract
      connection_id: bctob
    related_credentials:
      corporation:
        related_schema: contract_relationship.bcca
        topic: subcontract_id
        topic_name: subcontract_name
        related_topic: subcontractor_corp_num
        related_topic_name: legal_name
        effective_date: effective_date
        relationship_type: Sub-Contract
        relationship_description: Sub-Contract
        related_relationship_type: Sub-Contractor
        related_relationship_description: Sub-Contractor
      contract:
        related_schema: contract_relationship.bcca
        topic: subcontract_id
        topic_name: subcontract_name
        related_topic: contract_id
        related_topic_name: contract_name
        effective_date: effective_date
        relationship_type: Sub-Contract
        relationship_description: Sub-Contract
        related_relationship_type: Contract
        related_relationship_description: Contract
    fields:
    - name: subcontractor_corp_num
      label: subcontractor_corp_num
      type: text
      required: true
    - name: legal_name
      label: legal_name
      type: text
      required: true
    - name: contract_id
      label: contract_id
      type: text
      required: true
    - name: contract_name
      label: contract_name
      type: text
      required: true
    - name: subcontract_name
      label: subcontract_name
      type: text
      required: true
    - name: contract_type
      label: contract_type
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: contract_start_date
      label: contract_start_date
      type: date
      required: true
    - name: contract_end_date
      label: contract_end_date
      type: date
      required: true
    - name: payment_terms
      label: payment_terms
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: effective_date
      label: effective_date
      type: date
      required: true
    - name: expiry_date
      label: expiry_date
      type: date
      required: false
    mapping:
      attributes:
      - name: subcontract_id
        from: helper
        source: uuid
  bccacontractpayment:
    path: /bcca/contractpayment
    type: issue-credential
    schema_name: contract-payment.bcca
    page_title: Title for contract-payment.bcca
    title: Title for contract-payment.bcca
    template: bcgov.index.html
    description: The payment against the master contract
    explanation: Use the form below to issue a Credential.
    proof_request:
      id: bcca_contract
      connection_id: bctob
    fields:
    - name: contract_id
      label: contract_id
      type: text
      required: true
    - name: payment_type
      label: payment_type
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: amount_paid
      label: amount_paid
      type: text
      required: true
    - name: effective_date
      label: effective_date
      type: date
      required: true
    - name: expiry_date
      label: expiry_date
      type: date
      required: false
    mapping:
      attributes:
      - name: payment_id
        from: helper
        source: uuid
  bccacertificateofcompletion:
    path: /bcca/certificateofcompletion
    type: issue-credential
    schema_name: certificate-of-completion.bcca
    page_title: Title for certificate-of-completion.bcca
    title: Title for certificate-of-completion.bcca
    template: bcgov.index.html
    description: The certification that work has been completed per terms
    explanation: Use the form below to issue a Credential.
    proof_request:
      id: bcca_subcontract
      connection_id: bctob
    fields:
    - name: subcontract_id
      label: subcontract_id
      type: text
      required: true
    - name: payment_certifier
      label: payment_certifier
      type: text
      required: true
    - name: effective_date
      label: effective_date
      type: date
      required: true
    - name: expiry_date
      label: expiry_date
      type: date
      required: false
    mapping:
      attributes:
      - name: certification_id
        from: helper
        source: uuid
  bccacertificateofpayment:
    path: /bcca/certificateofpayment
    type: issue-credential
    schema_name: certificate-of-payment.bcca
    page_title: Title for certificate-of-payment.bcca
    title: Title for certificate-of-payment.bcca
    template: bcgov.index.html
    description: The certification that payment can be released per terms
    explanation: Use the form below to issue a Credential.
    proof_request:
      id: bcca_subcontract
      connection_id: bctob
    fields:
    - name: subcontract_id
      label: subcontract_id
      type: text
      required: true
    - name: certification_id
      label: certification_id
      type: text
      required: true
    - name: reference_number
      label: reference_number
      type: text
      required: true
    - name: amount_payable
      label: amount_payable
      type: text
      required: true
    - name: effective_date
      label: effective_date
      type: date
      required: true
    - name: expiry_date
      label: expiry_date
      type: date
      required: false
    mapping:
      attributes: []
  bccasubcontractpayment:
    path: /bcca/subcontractpayment
    type: issue-credential
    schema_name: subcontract-payment.bcca
    page_title: Title for subcontract-payment.bcca
    title: Title for subcontract-payment.bcca
    template: bcgov.index.html
    description: The payment against a sub-contract based on completion of work
    explanation: Use the form below to issue a Credential.
    proof_request:
      id: bcca_certificateofcompletion
      connection_id: bctob
    fields:
    - name: subcontract_id
      label: subcontract_id
      type: text
      required: true
    - name: certification_id
      label: certification_id
      type: text
      required: true
    - name: reference_number
      label: reference_number
      type: text
      required: true
    - name: payment_type
      label: payment_type
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: amount_paid
      label: amount_paid
      type: text
      required: true
    - name: effective_date
      label: effective_date
      type: date
      required: true
    - name: expiry_date
      label: expiry_date
      type: date
      required: false
    mapping:
      attributes:
      - name: payment_id
        from: helper
        source: uuid
  bccacontractor_relationship:
    path: /bcca/contractor_relationship
    type: issue-credential
    schema_name: contract_relationship.bcca
    page_title: Title for contract_relationship.bcca
    title: Title for contract_relationship.bcca
    template: bcgov.index.html
    description: Relationship between a Contract and the Client or General Contractor
    explanation: Use the form below to issue a Credential.
    fields:
    - name: source_id
      label: source_id
      type: text
      required: true
    - name: source_name
      label: source_name
      type: text
      required: true
    - name: associated_source_id
      label: associated_source_id
      type: text
      required: true
    - name: associated_source_name
      label: associated_source_name
      type: text
      required: true
    - name: relationship_type
      label: relationship_type
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: relationship_description
      label: relationship_description
      type: text
      required: true
    - name: effective_date
      label: effective_date
      type: date
      required: true
    - name: expiry_date
      label: expiry_date
      type: date
      required: false
    mapping:
      attributes: []
