issuers:
  myorg:
    credential_types:
    - description: The contract credential awarded to the General Contractor
      schema: contract.bcca
      issuer_url: $ENDPOINT_URL/bcca/contract
      depends_on:
      - dflow_registration
      credential:
        effective_date:
          input: effective_date
          from: claim
        revoked_date:
          input: expiry_date
          from: claim
      topic:
        source_id:
          input: contract_id
          from: claim
        type:
          input: registration
          from: value
      mapping:
      - model: attribute
        fields:
          type:
            input: corp_num
            from: value
          value:
            input: corp_num
            from: claim
      - model: attribute
        fields:
          type:
            input: legal_name
            from: value
          value:
            input: legal_name
            from: claim
      - model: attribute
        fields:
          type:
            input: contractor_corp_num
            from: value
          value:
            input: contractor_corp_num
            from: claim
      - model: attribute
        fields:
          type:
            input: contractor_legal_name
            from: value
          value:
            input: contractor_legal_name
            from: claim
      - model: attribute
        fields:
          type:
            input: contract_id
            from: value
          value:
            input: contract_id
            from: claim
      - model: name
        fields:
          text:
            input: contract_name
            from: claim
          type:
            input: contract_name
            from: value
      - model: attribute
        fields:
          type:
            input: permit_type
            from: value
          value:
            input: permit_type
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_issued_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: permit_issued_date
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_status
            from: value
          value:
            input: permit_status
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim
      - model: attribute
        fields:
          type:
            input: expiry_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: expiry_date
            from: claim
    - description: The sub-contract credential awarded to a Trade/Sub
      schema: subcontract.bcca
      issuer_url: $ENDPOINT_URL/bcca/subcontract
      depends_on:
      - bcca_contract
      credential:
        effective_date:
          input: effective_date
          from: claim
        revoked_date:
          input: expiry_date
          from: claim
      topic:
        source_id:
          input: subcontract_id
          from: claim
        type:
          input: registration
          from: value
      mapping:
      - model: attribute
        fields:
          type:
            input: subcontractor_corp_num
            from: value
          value:
            input: subcontractor_corp_num
            from: claim
      - model: attribute
        fields:
          type:
            input: legal_name
            from: value
          value:
            input: legal_name
            from: claim
      - model: attribute
        fields:
          type:
            input: contract_id
            from: value
          value:
            input: contract_id
            from: claim
      - model: attribute
        fields:
          type:
            input: subcontract_id
            from: value
          value:
            input: subcontract_id
            from: claim
      - model: name
        fields:
          text:
            input: subcontract_name
            from: claim
          type:
            input: subcontract_name
            from: value
      - model: attribute
        fields:
          type:
            input: permit_type
            from: value
          value:
            input: permit_type
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_issued_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: permit_issued_date
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_status
            from: value
          value:
            input: permit_status
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim
      - model: attribute
        fields:
          type:
            input: expiry_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: expiry_date
            from: claim
    - description: The payment against the master contract
      schema: contract-payment.bcca
      issuer_url: $ENDPOINT_URL/bcca/contractpayment
      depends_on:
      - bcca_contract
      credential:
        effective_date:
          input: effective_date
          from: claim
        revoked_date:
          input: expiry_date
          from: claim
      topic:
        source_id:
          input: contract_id
          from: claim
        type:
          input: registration
          from: value
      cardinality_fields:
      - payment_id
      mapping:
      - model: attribute
        fields:
          type:
            input: contract_id
            from: value
          value:
            input: contract_id
            from: claim
      - model: attribute
        fields:
          type:
            input: payment_id
            from: value
          value:
            input: payment_id
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_type
            from: value
          value:
            input: permit_type
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_issued_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: permit_issued_date
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_status
            from: value
          value:
            input: permit_status
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim
      - model: attribute
        fields:
          type:
            input: expiry_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: expiry_date
            from: claim
    - description: The certification that work has been completed per terms
      schema: certificate-of-completion.bcca
      issuer_url: $ENDPOINT_URL/bcca/certificateofcompletion
      depends_on:
      - bcca_subcontract
      credential:
        effective_date:
          input: effective_date
          from: claim
        revoked_date:
          input: expiry_date
          from: claim
      topic:
        source_id:
          input: subcontract_id
          from: claim
        type:
          input: registration
          from: value
      mapping:
      - model: attribute
        fields:
          type:
            input: subcontract_id
            from: value
          value:
            input: subcontract_id
            from: claim
      - model: attribute
        fields:
          type:
            input: certification_id
            from: value
          value:
            input: certification_id
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_type
            from: value
          value:
            input: permit_type
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_issued_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: permit_issued_date
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_status
            from: value
          value:
            input: permit_status
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim
      - model: attribute
        fields:
          type:
            input: expiry_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: expiry_date
            from: claim
    - description: The payment against a sub-contract based on completion of work
      schema: subcontract-payment.bcca
      issuer_url: $ENDPOINT_URL/bcca/subcontractpayment
      depends_on:
      - bcca_certificateofcompletion
      credential:
        effective_date:
          input: effective_date
          from: claim
        revoked_date:
          input: expiry_date
          from: claim
      topic:
        source_id:
          input: subcontract_id
          from: claim
        type:
          input: registration
          from: value
      mapping:
      - model: attribute
        fields:
          type:
            input: subcontract_id
            from: value
          value:
            input: subcontract_id
            from: claim
      - model: attribute
        fields:
          type:
            input: certification_id
            from: value
          value:
            input: certification_id
            from: claim
      - model: attribute
        fields:
          type:
            input: payment_id
            from: value
          value:
            input: payment_id
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_type
            from: value
          value:
            input: permit_type
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_issued_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: permit_issued_date
            from: claim
      - model: attribute
        fields:
          type:
            input: permit_status
            from: value
          value:
            input: permit_status
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim
      - model: attribute
        fields:
          type:
            input: expiry_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: expiry_date
            from: claim
    - description: Relationship between a Contract and the Client or General Contractor
      schema: contract_relationship.bcca
      issuer_url: $ENDPOINT_URL/bcca/contractor_relationship
      credential:
        effective_date:
          input: effective_date
          from: claim
        revoked_date:
          input: expiry_date
          from: claim
      topic:
        source_id:
          input: source_id
          from: claim
        type:
          input: registration
          from: value
        related_source_id:
          input: associated_source_id
          from: claim
        related_type:
          input: registration
          from: value
      cardinality_fields:
      - associated_source_id
      mapping:
      - model: attribute
        fields:
          type:
            input: source_id
            from: value
          value:
            input: source_id
            from: claim
      - model: attribute
        fields:
          type:
            input: source_name
            from: value
          value:
            input: source_name
            from: claim
      - model: attribute
        fields:
          type:
            input: associated_source_id
            from: value
          value:
            input: associated_source_id
            from: claim
      - model: attribute
        fields:
          type:
            input: associated_source_name
            from: value
          value:
            input: associated_source_name
            from: claim
      - model: attribute
        fields:
          type:
            input: relationship_type
            from: value
          value:
            input: relationship_type
            from: claim
      - model: attribute
        fields:
          type:
            input: relationship_description
            from: value
          value:
            input: relationship_description
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim
      - model: attribute
        fields:
          type:
            input: expiry_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: expiry_date
            from: claim
