forms:
  bccacontract:
    path: /bcca/contract
    type: issue-credential
    schema_name: contract.bcca
    page_title: Title for contract.bcca
    title: Title for contract.bcca
    template: bcgov.index.html
    description: The contract credential awarded to the General Contractor
    explanation: Use the form below to issue a Credential.
    proof_request:
      id: dflow_registration
      connection_id: bctob
    fields:
    - name: contract_name
      label: contract_name
      type: text
      required: true
    - name: legal_name
      label: legal_name
      type: text
      required: true
    - name: permit_status
      label: permit_status
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: contractor_legal_name
      label: contractor_legal_name
      type: text
      required: true
    - name: permit_type
      label: permit_type
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: permit_issued_date
      label: permit_issued_date
      type: date
      required: true
    - name: corp_num
      label: corp_num
      type: text
      required: true
    - name: expiry_date
      label: expiry_date
      type: date
      required: false
    - name: effective_date
      label: effective_date
      type: date
      required: true
    - name: contractor_corp_num
      label: contractor_corp_num
      type: text
      required: true
    - name: contract_location
      label: Mailing Address
      type: address
      required: true
    mapping:
      attributes:
      - name: contract_id
        from: helper
        source: uuid
  bccasubcontract:
    path: /bcca/subcontract
    type: issue-credential
    schema_name: subcontract.bcca
    page_title: Title for subcontract.bcca
    title: Title for subcontract.bcca
    template: bcgov.index.html
    description: The sub-contract credential awarded to a Trade/Sub
    explanation: Use the form below to issue a Credential.
    proof_request:
      id: bcca_contract
      connection_id: bctob
    fields:
    - name: legal_name
      label: legal_name
      type: text
      required: true
    - name: contract_id
      label: contract_id
      type: text
      required: true
    - name: permit_status
      label: permit_status
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: permit_type
      label: permit_type
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: permit_issued_date
      label: permit_issued_date
      type: date
      required: true
    - name: subcontractor_corp_num
      label: subcontractor_corp_num
      type: text
      required: true
    - name: expiry_date
      label: expiry_date
      type: date
      required: false
    - name: effective_date
      label: effective_date
      type: date
      required: true
    - name: subcontract_name
      label: subcontract_name
      type: text
      required: true
    mapping:
      attributes:
      - name: subcontract_id
        from: helper
        source: uuid
  bccacontractpayment:
    path: /bcca/contractpayment
    type: issue-credential
    schema_name: contract-payment.bcca
    page_title: Title for contract-payment.bcca
    title: Title for contract-payment.bcca
    template: bcgov.index.html
    description: The payment against the master contract
    explanation: Use the form below to issue a Credential.
    proof_request:
      id: bcca_contract
      connection_id: bctob
    fields:
    - name: permit_issued_date
      label: permit_issued_date
      type: date
      required: true
    - name: expiry_date
      label: expiry_date
      type: date
      required: false
    - name: contract_id
      label: contract_id
      type: text
      required: true
    - name: permit_status
      label: permit_status
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: effective_date
      label: effective_date
      type: date
      required: true
    - name: permit_type
      label: permit_type
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    mapping:
      attributes:
      - name: payment_id
        from: helper
        source: uuid
  bccacertificateofcompletion:
    path: /bcca/certificateofcompletion
    type: issue-credential
    schema_name: certificate-of-completion.bcca
    page_title: Title for certificate-of-completion.bcca
    title: Title for certificate-of-completion.bcca
    template: bcgov.index.html
    description: The certification that work has been completed per terms
    explanation: Use the form below to issue a Credential.
    proof_request:
      id: bcca_subcontract
      connection_id: bctob
    fields:
    - name: permit_issued_date
      label: permit_issued_date
      type: date
      required: true
    - name: expiry_date
      label: expiry_date
      type: date
      required: false
    - name: subcontract_id
      label: subcontract_id
      type: text
      required: true
    - name: permit_status
      label: permit_status
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: effective_date
      label: effective_date
      type: date
      required: true
    - name: permit_type
      label: permit_type
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    mapping:
      attributes:
      - name: certification_id
        from: helper
        source: uuid
  bccasubcontractpayment:
    path: /bcca/subcontractpayment
    type: issue-credential
    schema_name: subcontract-payment.bcca
    page_title: Title for subcontract-payment.bcca
    title: Title for subcontract-payment.bcca
    template: bcgov.index.html
    description: The payment against a sub-contract based on completion of work
    explanation: Use the form below to issue a Credential.
    proof_request:
      id: bcca_certificateofcompletion
      connection_id: bctob
    fields:
    - name: permit_status
      label: permit_status
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: certification_id
      label: certification_id
      type: text
      required: true
    - name: permit_type
      label: permit_type
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: permit_issued_date
      label: permit_issued_date
      type: date
      required: true
    - name: expiry_date
      label: expiry_date
      type: date
      required: false
    - name: subcontract_id
      label: subcontract_id
      type: text
      required: true
    - name: effective_date
      label: effective_date
      type: date
      required: true
    mapping:
      attributes:
      - name: payment_id
        from: helper
        source: uuid
  bccacontractor_relationship:
    path: /bcca/contractor_relationship
    type: issue-credential
    schema_name: contract_relationship.bcca
    page_title: Title for contract_relationship.bcca
    title: Title for contract_relationship.bcca
    template: bcgov.index.html
    description: Relationship between a Contract and the Client or General Contractor
    explanation: Use the form below to issue a Credential.
    fields:
    - name: associated_source_id
      label: associated_source_id
      type: text
      required: true
    - name: source_name
      label: source_name
      type: text
      required: true
    - name: relationship_type
      label: relationship_type
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: associated_source_name
      label: associated_source_name
      type: text
      required: true
    - name: expiry_date
      label: expiry_date
      type: date
      required: false
    - name: relationship_description
      label: relationship_description
      type: text
      required: true
    - name: effective_date
      label: effective_date
      type: date
      required: true
    - name: source_id
      label: source_id
      type: text
      required: true
    mapping:
      attributes: []
