# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

- name: ian-permit.ian-ville

  version: '1.0.0'
  description: The ian-permit credential issued by ian-cille
  path: /ian-ville/ian-permit

  attributes:
    - corp_num
    - legal_name
    - permit_id
    - permit_type
    - permit_issued_date
    - permit_status
    - effective_date

### eof ###

