forms:
  myorgtodo-credential2:
    path: /myorg/todo-credential2
    type: issue-credential
    schema_name: todo-rename-me2.my-organization.ca
    page_title: Title for todo-rename-me2.my-organization.ca
    title: Title for todo-rename-me2.my-organization.ca
    template: bcgov.index.html
    description: Describes the credential - depends on permitifys foundation credential
    explanation: Use the form below to issue a Credential.
    proof_request:
      id: permitify_registration
      connection_id: bctob
    fields:
    - name: corp_num
      label: corp_num
      type: text
      required: true
    - name: credential_text
      label: credential_text
      type: text
      required: true
    - name: credential_status
      label: credential_status
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: effective_date
      label: effective_date
      type: date
      required: true
    mappings:
      attributes:
      - name: credential_id
        from: helper
        source: uuid

### eof ###
